// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuPOAC69we6VVvN34oOP1D61IX6_Gb_u4',
    appId: '1:601243829747:web:86e1165ed4ea57c091be86',
    messagingSenderId: '601243829747',
    projectId: 'graduation-project-52094',
    authDomain: 'graduation-project-52094.firebaseapp.com',
    storageBucket: 'graduation-project-52094.appspot.com',
    measurementId: 'G-KRN59N9S2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4HRuaa8fm1R8CdzfpntjFi71XyGZqaa8',
    appId: '1:601243829747:android:559bbad8d9a4ce7291be86',
    messagingSenderId: '601243829747',
    projectId: 'graduation-project-52094',
    storageBucket: 'graduation-project-52094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3YK6AlZDA7MMLDic72es_Nsuo6BCzwRg',
    appId: '1:601243829747:ios:6a37332027c22aa891be86',
    messagingSenderId: '601243829747',
    projectId: 'graduation-project-52094',
    storageBucket: 'graduation-project-52094.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3YK6AlZDA7MMLDic72es_Nsuo6BCzwRg',
    appId: '1:601243829747:ios:09ea13e82bd2c2d291be86',
    messagingSenderId: '601243829747',
    projectId: 'graduation-project-52094',
    storageBucket: 'graduation-project-52094.appspot.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
